version: '3'

services:

  website:
    build: .
    ports:
      - "32741:3000"
    volumes:
      - ./data:/data/scfair
      - ./src:/opt/scfair
    env_file: .env.dev
   
  postgres:
    build: .
    env_file: .env.dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./startdb:/docker-entrypoint-initdb.d