version: '3'

services:

  website:
    build: .
    ports:
      - "32735:3000"
    volumes:
      - ./data:/data/tindex/
    env_file: .env.prod
   
  postgres:
    build:
        context: .
        dockerfile: Dockerfile.db
    env_file: .env.prod
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
