version: '3'

services:

  website:
    build: .
    ports:
      - "32735:3000"
    volumes:
      - ./data:/data/tindex/
    env_file: .env.prod
   
  postgres:
    image: postgres:15.4
    env_file: .env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
