development:
  solr:
    hostname: localhost
    port: 8984
    log_level: INFO
    path: /solr/test

test:
  solr:
    hostname: solr
    port: 8984
    log_level: WARNING
    path: /solr/test

production:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    path: /solr/production
